In [1]:
import numpy as np
import pandas as pd
import matplotlib.pyplot as plt
import warnings
warnings.filterwarnings('ignore')
print("All libraries imported successfully!")

All libraries imported successfully!

In [2]:
aqi = pd.read_excel('E:\\project_aqi_pulse\\data\\city_day.xlsx')
print("AQI Data Shape:", aqi.shape)
print("\n--- AQI First 5 Rows ---")
print(aqi.head())

AQI Data Shape: (29531, 16)

--- AQI First 5 Rows ---
        City       Date  PM2.5  PM10     NO    NO2    NOx  NH3     CO    SO2  \
0  Ahmedabad 2015-01-01    NaN   NaN   0.92  18.22  17.15  NaN   0.92  27.64
1  Ahmedabad 2015-01-02    NaN   NaN   0.97  15.69  16.46  NaN   0.97  24.55
2  Ahmedabad 2015-01-03    NaN   NaN  17.40  19.30  29.70  NaN  17.40  29.07
3  Ahmedabad 2015-01-04    NaN   NaN   1.70  18.48  17.97  NaN   1.70  18.59
4  Ahmedabad 2015-01-05    NaN   NaN  22.10  21.42  37.76  NaN  22.10  39.33

       O3  Benzene  Toluene  Xylene  AQI AQI_Bucket
0  133.36     0.00     0.02    0.00  NaN        NaN
1   34.06     3.68     5.50    3.77  NaN        NaN
2   30.70     6.80    16.40    2.25  NaN        NaN
3   36.08     4.43    10.14    1.00  NaN        NaN
4   39.31     7.01    18.89    2.78  NaN        NaN

In [3]:
print("=== Missing Values Check ===")
print(aqi.isnull().sum())
print("\n=== Data Types ===")
print(aqi.dtypes)

=== Missing Values Check ===
City              0
Date              0
PM2.5          4598
PM10          11140
NO             3582
NO2            3585
NOx            4185
NH3           10328
CO             2059
SO2            3854
O3             4022
Benzene        5623
Toluene        8041
Xylene        18109
AQI            4681
AQI_Bucket     4681
dtype: int64

=== Data Types ===
City                  object
Date          datetime64[ns]
PM2.5                float64
PM10                 float64
NO                   float64
NO2                  float64
NOx                  float64
NH3                  float64
CO                   float64
SO2                  float64
O3                   float64
Benzene              float64
Toluene              float64
Xylene               float64
AQI                  float64
AQI_Bucket            object
dtype: object

In [4]:
print(aqi.info())

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 29531 entries, 0 to 29530
Data columns (total 16 columns):
 #   Column      Non-Null Count  Dtype
---  ------      --------------  -----
 0   City        29531 non-null  object
 1   Date        29531 non-null  datetime64[ns]
 2   PM2.5       24933 non-null  float64
 3   PM10        18391 non-null  float64
 4   NO          25949 non-null  float64
 5   NO2         25946 non-null  float64
 6   NOx         25346 non-null  float64
 7   NH3         19203 non-null  float64
 8   CO          27472 non-null  float64
 9   SO2         25677 non-null  float64
 10  O3          25509 non-null  float64
 11  Benzene     23908 non-null  float64
 12  Toluene     21490 non-null  float64
 13  Xylene      11422 non-null  float64
 14  AQI         24850 non-null  float64
 15  AQI_Bucket  24850 non-null  object
dtypes: datetime64[ns](1), float64(13), object(2)
memory usage: 3.6+ MB
None

In [5]:
print(aqi.isnull().sum().sum())

88488

In [6]:
aqi = aqi.drop(columns=['Xylene', 'Benzene', 'Toluene', 'NOx'])

In [7]:
print(aqi.columns.tolist())

['City', 'Date', 'PM2.5', 'PM10', 'NO', 'NO2', 'NH3', 'CO', 'SO2', 'O3', 'AQI', 'AQI_Bucket']

In [8]:
aqi.dropna().reset_index(drop=True)
aqi

,City,Date,PM2.5,PM10,NO,NO2,NH3,CO,SO2,O3,AQI,AQI_Bucket
0,Ahmedabad,2015-01-01,NaN,NaN,0.92,18.22,NaN,0.92,27.64,133.36,NaN,NaN
1,Ahmedabad,2015-01-02,NaN,NaN,0.97,15.69,NaN,0.97,24.55,34.06,NaN,NaN
2,Ahmedabad,2015-01-03,NaN,NaN,17.40,19.30,NaN,17.40,29.07,30.70,NaN,NaN
3,Ahmedabad,2015-01-04,NaN,NaN,1.70,18.48,NaN,1.70,18.59,36.08,NaN,NaN
4,Ahmedabad,2015-01-05,NaN,NaN,22.10,21.42,NaN,22.10,39.33,39.31,NaN,NaN
...,...,...,...,...,...,...,...,...,...,...,...,...
29526,Visakhapatnam,2020-06-27,15.02,50.94,7.68,25.06,12.47,0.47,8.55,23.30,41.0,Good
29527,Visakhapatnam,2020-06-28,24.38,74.09,3.42,26.06,11.99,0.52,12.72,30.14,70.0,Satisfactory
29528,Visakhapatnam,2020-06-29,22.91,65.73,3.45,29.53,10.71,0.48,8.42,30.96,68.0,Satisfactory
29529,Visakhapatnam,2020-06-30,16.64,49.97,4.05,29.26,10.03,0.52,9.84,28.30,54.0,Satisfactory
29530,Visakhapatnam,2020-07-01,15.00,66.00,0.40,26.85,5.20,0.59,2.10,17.05,50.0,Good

In [9]:
aqi.head()

,City,Date,PM2.5,PM10,NO,NO2,NH3,CO,SO2,O3,AQI,AQI_Bucket
0,Ahmedabad,2015-01-01,NaN,NaN,0.92,18.22,NaN,0.92,27.64,133.36,NaN,NaN
1,Ahmedabad,2015-01-02,NaN,NaN,0.97,15.69,NaN,0.97,24.55,34.06,NaN,NaN
2,Ahmedabad,2015-01-03,NaN,NaN,17.40,19.30,NaN,17.40,29.07,30.70,NaN,NaN
3,Ahmedabad,2015-01-04,NaN,NaN,1.70,18.48,NaN,1.70,18.59,36.08,NaN,NaN
4,Ahmedabad,2015-01-05,NaN,NaN,22.10,21.42,NaN,22.10,39.33,39.31,NaN,NaN

In [10]:
aqi.shape

(29531, 12)

In [11]:
aqi.dropna(subset=['AQI'])

,City,Date,PM2.5,PM10,NO,NO2,NH3,CO,SO2,O3,AQI,AQI_Bucket
28,Ahmedabad,2015-01-29,83.13,NaN,6.93,28.71,NaN,6.93,49.52,59.76,209.0,Poor
29,Ahmedabad,2015-01-30,79.84,NaN,13.85,28.68,NaN,13.85,48.49,97.07,328.0,Very Poor
30,Ahmedabad,2015-01-31,94.52,NaN,24.39,32.66,NaN,24.39,67.39,111.33,514.0,Severe
31,Ahmedabad,2015-02-01,135.99,NaN,43.48,42.08,NaN,43.48,75.23,102.70,782.0,Severe
32,Ahmedabad,2015-02-02,178.33,NaN,54.56,35.31,NaN,54.56,55.04,107.38,914.0,Severe
...,...,...,...,...,...,...,...,...,...,...,...,...
29526,Visakhapatnam,2020-06-27,15.02,50.94,7.68,25.06,12.47,0.47,8.55,23.30,41.0,Good
29527,Visakhapatnam,2020-06-28,24.38,74.09,3.42,26.06,11.99,0.52,12.72,30.14,70.0,Satisfactory
29528,Visakhapatnam,2020-06-29,22.91,65.73,3.45,29.53,10.71,0.48,8.42,30.96,68.0,Satisfactory
29529,Visakhapatnam,2020-06-30,16.64,49.97,4.05,29.26,10.03,0.52,9.84,28.30,54.0,Satisfactory
29530,Visakhapatnam,2020-07-01,15.00,66.00,0.40,26.85,5.20,0.59,2.10,17.05,50.0,Good

In [12]:
aqi.reset_index()

,index,City,Date,PM2.5,PM10,NO,NO2,NH3,CO,SO2,O3,AQI,AQI_Bucket
0,0,Ahmedabad,2015-01-01,NaN,NaN,0.92,18.22,NaN,0.92,27.64,133.36,NaN,NaN
1,1,Ahmedabad,2015-01-02,NaN,NaN,0.97,15.69,NaN,0.97,24.55,34.06,NaN,NaN
2,2,Ahmedabad,2015-01-03,NaN,NaN,17.40,19.30,NaN,17.40,29.07,30.70,NaN,NaN
3,3,Ahmedabad,2015-01-04,NaN,NaN,1.70,18.48,NaN,1.70,18.59,36.08,NaN,NaN
4,4,Ahmedabad,2015-01-05,NaN,NaN,22.10,21.42,NaN,22.10,39.33,39.31,NaN,NaN
...,...,...,...,...,...,...,...,...,...,...,...,...,...
29526,29526,Visakhapatnam,2020-06-27,15.02,50.94,7.68,25.06,12.47,0.47,8.55,23.30,41.0,Good
29527,29527,Visakhapatnam,2020-06-28,24.38,74.09,3.42,26.06,11.99,0.52,12.72,30.14,70.0,Satisfactory
29528,29528,Visakhapatnam,2020-06-29,22.91,65.73,3.45,29.53,10.71,0.48,8.42,30.96,68.0,Satisfactory
29529,29529,Visakhapatnam,2020-06-30,16.64,49.97,4.05,29.26,10.03,0.52,9.84,28.30,54.0,Satisfactory
29530,29530,Visakhapatnam,2020-07-01,15.00,66.00,0.40,26.85,5.20,0.59,2.10,17.05,50.0,Good

In [13]:
aqi = aqi.dropna(subset=['AQI']).reset_index(drop=True)
aqi

,City,Date,PM2.5,PM10,NO,NO2,NH3,CO,SO2,O3,AQI,AQI_Bucket
0,Ahmedabad,2015-01-29,83.13,NaN,6.93,28.71,NaN,6.93,49.52,59.76,209.0,Poor
1,Ahmedabad,2015-01-30,79.84,NaN,13.85,28.68,NaN,13.85,48.49,97.07,328.0,Very Poor
2,Ahmedabad,2015-01-31,94.52,NaN,24.39,32.66,NaN,24.39,67.39,111.33,514.0,Severe
3,Ahmedabad,2015-02-01,135.99,NaN,43.48,42.08,NaN,43.48,75.23,102.70,782.0,Severe
4,Ahmedabad,2015-02-02,178.33,NaN,54.56,35.31,NaN,54.56,55.04,107.38,914.0,Severe
...,...,...,...,...,...,...,...,...,...,...,...,...
24845,Visakhapatnam,2020-06-27,15.02,50.94,7.68,25.06,12.47,0.47,8.55,23.30,41.0,Good
24846,Visakhapatnam,2020-06-28,24.38,74.09,3.42,26.06,11.99,0.52,12.72,30.14,70.0,Satisfactory
24847,Visakhapatnam,2020-06-29,22.91,65.73,3.45,29.53,10.71,0.48,8.42,30.96,68.0,Satisfactory
24848,Visakhapatnam,2020-06-30,16.64,49.97,4.05,29.26,10.03,0.52,9.84,28.30,54.0,Satisfactory
24849,Visakhapatnam,2020-07-01,15.00,66.00,0.40,26.85,5.20,0.59,2.10,17.05,50.0,Good

In [14]:
print(aqi.head(50))

         City       Date   PM2.5  PM10     NO    NO2  NH3     CO     SO2  \
0   Ahmedabad 2015-01-29   83.13   NaN   6.93  28.71  NaN   6.93   49.52
1   Ahmedabad 2015-01-30   79.84   NaN  13.85  28.68  NaN  13.85   48.49
2   Ahmedabad 2015-01-31   94.52   NaN  24.39  32.66  NaN  24.39   67.39
3   Ahmedabad 2015-02-01  135.99   NaN  43.48  42.08  NaN  43.48   75.23
4   Ahmedabad 2015-02-02  178.33   NaN  54.56  35.31  NaN  54.56   55.04
5   Ahmedabad 2015-02-03  139.70   NaN  30.61  28.40  NaN  30.61   33.79
6   Ahmedabad 2015-02-04   80.65   NaN   2.37  22.83  NaN   2.37   25.73
7   Ahmedabad 2015-02-05   58.36   NaN   2.60  21.39  NaN   2.60   32.66
8   Ahmedabad 2015-02-06   79.29   NaN   1.16  26.94  NaN   1.16   67.41
9   Ahmedabad 2015-02-07   88.70   NaN   7.29  31.32  NaN   7.29   80.09
10  Ahmedabad 2015-02-08   74.28   NaN   8.92  27.30  NaN   8.92   54.28
11  Ahmedabad 2015-02-09  113.93   NaN   4.32  24.27  NaN   4.32   48.73
12  Ahmedabad 2015-02-10  105.39   NaN   1.41  18.21  NaN   1.41   35.91
13  Ahmedabad 2015-02-11   66.52   NaN   6.34  23.80  NaN   6.34   66.58
14  Ahmedabad 2015-02-12   65.04   NaN  14.19  30.10  NaN  14.19   65.91
15  Ahmedabad 2015-02-13  103.36   NaN  18.18  39.56  NaN  18.18   80.43
16  Ahmedabad 2015-02-14  177.33   NaN  37.49  47.58  NaN  37.49   99.72
17  Ahmedabad 2015-02-15  113.25   NaN  15.55  30.50  NaN  15.55   69.71
18  Ahmedabad 2015-02-16   99.70   NaN  19.85  28.10  NaN  19.85   73.23
19  Ahmedabad 2015-02-17   80.61   NaN  15.96  21.04  NaN  15.96   54.70
20  Ahmedabad 2015-02-18  100.79   NaN  16.24  25.93  NaN  16.24   43.11
21  Ahmedabad 2015-02-19  107.99   NaN  11.25  30.09  NaN  11.25   84.86
22  Ahmedabad 2015-02-20  140.29   NaN  33.84  36.14  NaN  33.84  101.53
23  Ahmedabad 2015-02-21  239.96   NaN  61.95  46.25  NaN  61.95   84.87
24  Ahmedabad 2015-02-22  142.96   NaN  45.45  48.21  NaN  45.45   62.96
25  Ahmedabad 2015-02-23  238.41   NaN  77.70  55.07  NaN  77.70   89.07
26  Ahmedabad 2015-02-24  118.72   NaN  12.56  32.01  NaN  12.56   61.54
27  Ahmedabad 2015-02-25   52.99   NaN   2.23  10.45  NaN   2.23   32.76
28  Ahmedabad 2015-03-02   60.78   NaN   9.07  18.21  NaN   9.07   29.48
29  Ahmedabad 2015-03-03   91.83   NaN  12.99  28.71  NaN  12.99   39.71
30  Ahmedabad 2015-03-04   93.88   NaN  18.21  29.38  NaN  18.21   62.75
31  Ahmedabad 2015-03-05  173.01   NaN  48.44  42.27  NaN  48.44   78.76
32  Ahmedabad 2015-03-08   71.56   NaN   3.51  16.83  NaN   3.51   30.28
33  Ahmedabad 2015-03-09  119.80   NaN   4.13  24.07  NaN   4.13   50.35
34  Ahmedabad 2015-03-10  106.71   NaN   5.39  25.59  NaN   5.39   38.85
35  Ahmedabad 2015-03-11  118.49   NaN   4.11  28.94  NaN   4.11   54.20
36  Ahmedabad 2015-03-12  106.01   NaN   4.28  27.31  NaN   4.28   70.29
37  Ahmedabad 2015-03-13   97.34   NaN   3.67  21.58  NaN   3.67   64.39
38  Ahmedabad 2015-03-14   83.92   NaN   6.42  25.03  NaN   6.42   67.53
39  Ahmedabad 2015-03-15   49.51   NaN   3.10  14.16  NaN   3.10   48.33
40  Ahmedabad 2015-03-16   30.76   NaN   2.72  14.14  NaN   2.72   43.62
41  Ahmedabad 2015-03-17   50.29   NaN   5.34  29.84  NaN   5.34   59.23
42  Ahmedabad 2015-03-18   57.69   NaN  25.36  29.48  NaN  25.36   58.33
43  Ahmedabad 2015-03-19  105.06   NaN  46.24  37.05  NaN  46.24   53.62
44  Ahmedabad 2015-03-20   94.10   NaN  22.14  36.53  NaN  22.14   61.31
45  Ahmedabad 2015-03-21  111.89   NaN  22.25  43.29  NaN  22.25   66.44
46  Ahmedabad 2015-03-22  108.59   NaN  25.38  39.34  NaN  25.38   75.80
47  Ahmedabad 2015-03-23  130.76   NaN  45.61  41.03  NaN  45.61   65.77
48  Ahmedabad 2015-03-24  143.55   NaN  27.30  31.15  NaN  27.30   50.98
49  Ahmedabad 2015-03-25  165.07   NaN  23.83  34.48  NaN  23.83   64.32

        O3     AQI AQI_Bucket
0    59.76   209.0       Poor
1    97.07   328.0  Very Poor
2   111.33   514.0     Severe
3   102.70   782.0     Severe
4   107.38   914.0     Severe
5    73.60   660.0     Severe
6    47.30   294.0       Poor
7    53.54   149.0   Moderate
8    59.30   190.0   Moderate
9    44.76   247.0       Poor
10   47.42   379.0  Very Poor
11   39.94   341.0  Very Poor
12   56.15   256.0       Poor
13   53.14   388.0  Very Poor
14   31.88   288.0       Poor
15   40.11   510.0     Severe
16   36.47   761.0     Severe
17   33.78   475.0     Severe
18   30.57   536.0     Severe
19   36.20   479.0     Severe
20   37.43   592.0     Severe
21   31.94   427.0     Severe
22   40.98   588.0     Severe
23   33.55  1141.0     Severe
24   34.77   669.0     Severe
25   37.30  1247.0     Severe
26   38.80   411.0     Severe
27   67.25   292.0       Poor
28   34.75   189.0   Moderate
29   38.46   408.0     Severe
30   46.79   383.0  Very Poor
31   59.39   780.0     Severe
32   57.16   190.0   Moderate
33   50.49   233.0       Poor
34   60.17   297.0       Poor
35   53.61   330.0  Very Poor
36   40.91   252.0       Poor
37   45.69   244.0       Poor
38   34.94   234.0       Poor
39   37.95   219.0       Poor
40   54.78   118.0   Moderate
41   45.44   231.0       Poor
42   52.87   286.0       Poor
43   45.65   883.0     Severe
44   46.77   720.0     Severe
45   50.57   570.0     Severe
46   46.68   589.0     Severe
47   41.58   818.0     Severe
48   35.38   737.0     Severe
49   43.79   585.0     Severe

In [15]:
aqi['Date'] = pd.to_datetime(aqi['Date'], format='%B-%Y')
aqi

,City,Date,PM2.5,PM10,NO,NO2,NH3,CO,SO2,O3,AQI,AQI_Bucket
0,Ahmedabad,2015-01-29,83.13,NaN,6.93,28.71,NaN,6.93,49.52,59.76,209.0,Poor
1,Ahmedabad,2015-01-30,79.84,NaN,13.85,28.68,NaN,13.85,48.49,97.07,328.0,Very Poor
2,Ahmedabad,2015-01-31,94.52,NaN,24.39,32.66,NaN,24.39,67.39,111.33,514.0,Severe
3,Ahmedabad,2015-02-01,135.99,NaN,43.48,42.08,NaN,43.48,75.23,102.70,782.0,Severe
4,Ahmedabad,2015-02-02,178.33,NaN,54.56,35.31,NaN,54.56,55.04,107.38,914.0,Severe
...,...,...,...,...,...,...,...,...,...,...,...,...
24845,Visakhapatnam,2020-06-27,15.02,50.94,7.68,25.06,12.47,0.47,8.55,23.30,41.0,Good
24846,Visakhapatnam,2020-06-28,24.38,74.09,3.42,26.06,11.99,0.52,12.72,30.14,70.0,Satisfactory
24847,Visakhapatnam,2020-06-29,22.91,65.73,3.45,29.53,10.71,0.48,8.42,30.96,68.0,Satisfactory
24848,Visakhapatnam,2020-06-30,16.64,49.97,4.05,29.26,10.03,0.52,9.84,28.30,54.0,Satisfactory
24849,Visakhapatnam,2020-07-01,15.00,66.00,0.40,26.85,5.20,0.59,2.10,17.05,50.0,Good

In [16]:
print("Date range:", aqi['Date'].min(), "to", aqi['Date'].max())

Date range: 2015-01-01 00:00:00 to 2020-07-01 00:00:00

In [17]:
aqi['Month'] = aqi['Date'].dt.month
aqi['Year'] = aqi['Date'].dt.year

In [18]:
aqi

,City,Date,PM2.5,PM10,NO,NO2,NH3,CO,SO2,O3,AQI,AQI_Bucket,Month,Year
0,Ahmedabad,2015-01-29,83.13,NaN,6.93,28.71,NaN,6.93,49.52,59.76,209.0,Poor,1,2015
1,Ahmedabad,2015-01-30,79.84,NaN,13.85,28.68,NaN,13.85,48.49,97.07,328.0,Very Poor,1,2015
2,Ahmedabad,2015-01-31,94.52,NaN,24.39,32.66,NaN,24.39,67.39,111.33,514.0,Severe,1,2015
3,Ahmedabad,2015-02-01,135.99,NaN,43.48,42.08,NaN,43.48,75.23,102.70,782.0,Severe,2,2015
4,Ahmedabad,2015-02-02,178.33,NaN,54.56,35.31,NaN,54.56,55.04,107.38,914.0,Severe,2,2015
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
24845,Visakhapatnam,2020-06-27,15.02,50.94,7.68,25.06,12.47,0.47,8.55,23.30,41.0,Good,6,2020
24846,Visakhapatnam,2020-06-28,24.38,74.09,3.42,26.06,11.99,0.52,12.72,30.14,70.0,Satisfactory,6,2020
24847,Visakhapatnam,2020-06-29,22.91,65.73,3.45,29.53,10.71,0.48,8.42,30.96,68.0,Satisfactory,6,2020
24848,Visakhapatnam,2020-06-30,16.64,49.97,4.05,29.26,10.03,0.52,9.84,28.30,54.0,Satisfactory,6,2020
24849,Visakhapatnam,2020-07-01,15.00,66.00,0.40,26.85,5.20,0.59,2.10,17.05,50.0,Good,7,2020

In [19]:
aqi = aqi[['City', 'Date', 'Month', 'Year', 'PM2.5', 'PM10', 'NO', 'NO2', 'NH3', 'CO', 'SO2', 'O3', 'AQI', 'AQI_Bucket']]
aqi

,City,Date,Month,Year,PM2.5,PM10,NO,NO2,NH3,CO,SO2,O3,AQI,AQI_Bucket
0,Ahmedabad,2015-01-29,1,2015,83.13,NaN,6.93,28.71,NaN,6.93,49.52,59.76,209.0,Poor
1,Ahmedabad,2015-01-30,1,2015,79.84,NaN,13.85,28.68,NaN,13.85,48.49,97.07,328.0,Very Poor
2,Ahmedabad,2015-01-31,1,2015,94.52,NaN,24.39,32.66,NaN,24.39,67.39,111.33,514.0,Severe
3,Ahmedabad,2015-02-01,2,2015,135.99,NaN,43.48,42.08,NaN,43.48,75.23,102.70,782.0,Severe
4,Ahmedabad,2015-02-02,2,2015,178.33,NaN,54.56,35.31,NaN,54.56,55.04,107.38,914.0,Severe
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
24845,Visakhapatnam,2020-06-27,6,2020,15.02,50.94,7.68,25.06,12.47,0.47,8.55,23.30,41.0,Good
24846,Visakhapatnam,2020-06-28,6,2020,24.38,74.09,3.42,26.06,11.99,0.52,12.72,30.14,70.0,Satisfactory
24847,Visakhapatnam,2020-06-29,6,2020,22.91,65.73,3.45,29.53,10.71,0.48,8.42,30.96,68.0,Satisfactory
24848,Visakhapatnam,2020-06-30,6,2020,16.64,49.97,4.05,29.26,10.03,0.52,9.84,28.30,54.0,Satisfactory
24849,Visakhapatnam,2020-07-01,7,2020,15.00,66.00,0.40,26.85,5.20,0.59,2.10,17.05,50.0,Good

In [20]:
conditions = [
    aqi['Month'].isin([12, 1, 2]),
    aqi['Month'].isin([3, 4, 5]),
    aqi['Month'].isin([6, 7, 8, 9]),
    aqi['Month'].isin([10, 11])
]

choices = ['Winter', 'Summer', 'Monsoon', 'Post-Monsoon']

aqi['Season'] = np.select(conditions, choices, default='unknown')
aqi

,City,Date,Month,Year,PM2.5,PM10,NO,NO2,NH3,CO,SO2,O3,AQI,AQI_Bucket,Season
0,Ahmedabad,2015-01-29,1,2015,83.13,NaN,6.93,28.71,NaN,6.93,49.52,59.76,209.0,Poor,Winter
1,Ahmedabad,2015-01-30,1,2015,79.84,NaN,13.85,28.68,NaN,13.85,48.49,97.07,328.0,Very Poor,Winter
2,Ahmedabad,2015-01-31,1,2015,94.52,NaN,24.39,32.66,NaN,24.39,67.39,111.33,514.0,Severe,Winter
3,Ahmedabad,2015-02-01,2,2015,135.99,NaN,43.48,42.08,NaN,43.48,75.23,102.70,782.0,Severe,Winter
4,Ahmedabad,2015-02-02,2,2015,178.33,NaN,54.56,35.31,NaN,54.56,55.04,107.38,914.0,Severe,Winter
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
24845,Visakhapatnam,2020-06-27,6,2020,15.02,50.94,7.68,25.06,12.47,0.47,8.55,23.30,41.0,Good,Monsoon
24846,Visakhapatnam,2020-06-28,6,2020,24.38,74.09,3.42,26.06,11.99,0.52,12.72,30.14,70.0,Satisfactory,Monsoon
24847,Visakhapatnam,2020-06-29,6,2020,22.91,65.73,3.45,29.53,10.71,0.48,8.42,30.96,68.0,Satisfactory,Monsoon
24848,Visakhapatnam,2020-06-30,6,2020,16.64,49.97,4.05,29.26,10.03,0.52,9.84,28.30,54.0,Satisfactory,Monsoon
24849,Visakhapatnam,2020-07-01,7,2020,15.00,66.00,0.40,26.85,5.20,0.59,2.10,17.05,50.0,Good,Monsoon

In [21]:
aqi = aqi[['City', 'Date', 'Month', 'Year', 'Season', 'PM2.5', 'PM10', 'NO', 'NO2', 'NH3', 'CO', 'SO2', 'O3', 'AQI', 'AQI_Bucket']]

In [22]:
aqi

,City,Date,Month,Year,Season,PM2.5,PM10,NO,NO2,NH3,CO,SO2,O3,AQI,AQI_Bucket
0,Ahmedabad,2015-01-29,1,2015,Winter,83.13,NaN,6.93,28.71,NaN,6.93,49.52,59.76,209.0,Poor
1,Ahmedabad,2015-01-30,1,2015,Winter,79.84,NaN,13.85,28.68,NaN,13.85,48.49,97.07,328.0,Very Poor
2,Ahmedabad,2015-01-31,1,2015,Winter,94.52,NaN,24.39,32.66,NaN,24.39,67.39,111.33,514.0,Severe
3,Ahmedabad,2015-02-01,2,2015,Winter,135.99,NaN,43.48,42.08,NaN,43.48,75.23,102.70,782.0,Severe
4,Ahmedabad,2015-02-02,2,2015,Winter,178.33,NaN,54.56,35.31,NaN,54.56,55.04,107.38,914.0,Severe
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
24845,Visakhapatnam,2020-06-27,6,2020,Monsoon,15.02,50.94,7.68,25.06,12.47,0.47,8.55,23.30,41.0,Good
24846,Visakhapatnam,2020-06-28,6,2020,Monsoon,24.38,74.09,3.42,26.06,11.99,0.52,12.72,30.14,70.0,Satisfactory
24847,Visakhapatnam,2020-06-29,6,2020,Monsoon,22.91,65.73,3.45,29.53,10.71,0.48,8.42,30.96,68.0,Satisfactory
24848,Visakhapatnam,2020-06-30,6,2020,Monsoon,16.64,49.97,4.05,29.26,10.03,0.52,9.84,28.30,54.0,Satisfactory
24849,Visakhapatnam,2020-07-01,7,2020,Monsoon,15.00,66.00,0.40,26.85,5.20,0.59,2.10,17.05,50.0,Good

In [23]:
aqi['PM2.5'] = aqi['PM2.5'].fillna(
    aqi.groupby(['City', 'Month'])['PM2.5'].transform('mean')
)

aqi.head(100)

,City,Date,Month,Year,Season,PM2.5,PM10,NO,NO2,NH3,CO,SO2,O3,AQI,AQI_Bucket
0,Ahmedabad,2015-01-29,1,2015,Winter,83.13,NaN,6.93,28.71,NaN,6.93,49.52,59.76,209.0,Poor
1,Ahmedabad,2015-01-30,1,2015,Winter,79.84,NaN,13.85,28.68,NaN,13.85,48.49,97.07,328.0,Very Poor
2,Ahmedabad,2015-01-31,1,2015,Winter,94.52,NaN,24.39,32.66,NaN,24.39,67.39,111.33,514.0,Severe
3,Ahmedabad,2015-02-01,2,2015,Winter,135.99,NaN,43.48,42.08,NaN,43.48,75.23,102.70,782.0,Severe
4,Ahmedabad,2015-02-02,2,2015,Winter,178.33,NaN,54.56,35.31,NaN,54.56,55.04,107.38,914.0,Severe
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
95,Ahmedabad,2015-05-15,5,2015,Summer,129.27,NaN,14.28,28.33,NaN,14.28,70.13,25.40,327.0,Very Poor
96,Ahmedabad,2015-05-16,5,2015,Summer,129.58,NaN,21.23,28.79,NaN,21.23,17.66,34.42,577.0,Severe
97,Ahmedabad,2015-05-17,5,2015,Summer,100.57,NaN,7.56,18.79,NaN,7.56,38.76,38.83,411.0,Severe
98,Ahmedabad,2015-05-18,5,2015,Summer,130.34,NaN,7.14,17.43,NaN,7.14,52.07,29.05,212.0,Poor
99,Ahmedabad,2015-05-19,5,2015,Summer,53.24,NaN,8.05,15.86,NaN,8.05,36.23,21.58,280.0,Poor

In [24]:
columns_to_fill = ['PM10', 'NO', 'NO2', 'NH3', 'CO', 'SO2', 'O3']

for col in columns_to_fill:
    aqi[col] = aqi[col].fillna(
        aqi.groupby(['City', 'Month'])[col].transform('mean')
    )

In [25]:
aqi.head(50)

,City,Date,Month,Year,Season,PM2.5,PM10,NO,NO2,NH3,CO,SO2,O3,AQI,AQI_Bucket
0,Ahmedabad,2015-01-29,1,2015,Winter,83.13,111.684815,6.93,28.71,NaN,6.93,49.52,59.76,209.0,Poor
1,Ahmedabad,2015-01-30,1,2015,Winter,79.84,111.684815,13.85,28.68,NaN,13.85,48.49,97.07,328.0,Very Poor
2,Ahmedabad,2015-01-31,1,2015,Winter,94.52,111.684815,24.39,32.66,NaN,24.39,67.39,111.33,514.0,Severe
3,Ahmedabad,2015-02-01,2,2015,Winter,135.99,144.907931,43.48,42.08,NaN,43.48,75.23,102.70,782.0,Severe
4,Ahmedabad,2015-02-02,2,2015,Winter,178.33,144.907931,54.56,35.31,NaN,54.56,55.04,107.38,914.0,Severe
5,Ahmedabad,2015-02-03,2,2015,Winter,139.70,144.907931,30.61,28.40,NaN,30.61,33.79,73.60,660.0,Severe
6,Ahmedabad,2015-02-04,2,2015,Winter,80.65,144.907931,2.37,22.83,NaN,2.37,25.73,47.30,294.0,Poor
7,Ahmedabad,2015-02-05,2,2015,Winter,58.36,144.907931,2.60,21.39,NaN,2.60,32.66,53.54,149.0,Moderate
8,Ahmedabad,2015-02-06,2,2015,Winter,79.29,144.907931,1.16,26.94,NaN,1.16,67.41,59.30,190.0,Moderate
9,Ahmedabad,2015-02-07,2,2015,Winter,88.70,144.907931,7.29,31.32,NaN,7.29,80.09,44.76,247.0,Poor
10,Ahmedabad,2015-02-08,2,2015,Winter,74.28,144.907931,8.92,27.30,NaN,8.92,54.28,47.42,379.0,Very Poor
11,Ahmedabad,2015-02-09,2,2015,Winter,113.93,144.907931,4.32,24.27,NaN,4.32,48.73,39.94,341.0,Very Poor
12,Ahmedabad,2015-02-10,2,2015,Winter,105.39,144.907931,1.41,18.21,NaN,1.41,35.91,56.15,256.0,Poor
13,Ahmedabad,2015-02-11,2,2015,Winter,66.52,144.907931,6.34,23.80,NaN,6.34,66.58,53.14,388.0,Very Poor
14,Ahmedabad,2015-02-12,2,2015,Winter,65.04,144.907931,14.19,30.10,NaN,14.19,65.91,31.88,288.0,Poor
15,Ahmedabad,2015-02-13,2,2015,Winter,103.36,144.907931,18.18,39.56,NaN,18.18,80.43,40.11,510.0,Severe
16,Ahmedabad,2015-02-14,2,2015,Winter,177.33,144.907931,37.49,47.58,NaN,37.49,99.72,36.47,761.0,Severe
17,Ahmedabad,2015-02-15,2,2015,Winter,113.25,144.907931,15.55,30.50,NaN,15.55,69.71,33.78,475.0,Severe
18,Ahmedabad,2015-02-16,2,2015,Winter,99.70,144.907931,19.85,28.10,NaN,19.85,73.23,30.57,536.0,Severe
19,Ahmedabad,2015-02-17,2,2015,Winter,80.61,144.907931,15.96,21.04,NaN,15.96,54.70,36.20,479.0,Severe
20,Ahmedabad,2015-02-18,2,2015,Winter,100.79,144.907931,16.24,25.93,NaN,16.24,43.11,37.43,592.0,Severe
21,Ahmedabad,2015-02-19,2,2015,Winter,107.99,144.907931,11.25,30.09,NaN,11.25,84.86,31.94,427.0,Severe
22,Ahmedabad,2015-02-20,2,2015,Winter,140.29,144.907931,33.84,36.14,NaN,33.84,101.53,40.98,588.0,Severe
23,Ahmedabad,2015-02-21,2,2015,Winter,239.96,144.907931,61.95,46.25,NaN,61.95,84.87,33.55,1141.0,Severe
24,Ahmedabad,2015-02-22,2,2015,Winter,142.96,144.907931,45.45,48.21,NaN,45.45,62.96,34.77,669.0,Severe
25,Ahmedabad,2015-02-23,2,2015,Winter,238.41,144.907931,77.70,55.07,NaN,77.70,89.07,37.30,1247.0,Severe
26,Ahmedabad,2015-02-24,2,2015,Winter,118.72,144.907931,12.56,32.01,NaN,12.56,61.54,38.80,411.0,Severe
27,Ahmedabad,2015-02-25,2,2015,Winter,52.99,144.907931,2.23,10.45,NaN,2.23,32.76,67.25,292.0,Poor
28,Ahmedabad,2015-03-02,3,2015,Summer,60.78,108.015667,9.07,18.21,NaN,9.07,29.48,34.75,189.0,Moderate
29,Ahmedabad,2015-03-03,3,2015,Summer,91.83,108.015667,12.99,28.71,NaN,12.99,39.71,38.46,408.0,Severe
30,Ahmedabad,2015-03-04,3,2015,Summer,93.88,108.015667,18.21,29.38,NaN,18.21,62.75,46.79,383.0,Very Poor
31,Ahmedabad,2015-03-05,3,2015,Summer,173.01,108.015667,48.44,42.27,NaN,48.44,78.76,59.39,780.0,Severe
32,Ahmedabad,2015-03-08,3,2015,Summer,71.56,108.015667,3.51,16.83,NaN,3.51,30.28,57.16,190.0,Moderate
33,Ahmedabad,2015-03-09,3,2015,Summer,119.80,108.015667,4.13,24.07,NaN,4.13,50.35,50.49,233.0,Poor
34,Ahmedabad,2015-03-10,3,2015,Summer,106.71,108.015667,5.39,25.59,NaN,5.39,38.85,60.17,297.0,Poor
35,Ahmedabad,2015-03-11,3,2015,Summer,118.49,108.015667,4.11,28.94,NaN,4.11,54.20,53.61,330.0,Very Poor
36,Ahmedabad,2015-03-12,3,2015,Summer,106.01,108.015667,4.28,27.31,NaN,4.28,70.29,40.91,252.0,Poor
37,Ahmedabad,2015-03-13,3,2015,Summer,97.34,108.015667,3.67,21.58,NaN,3.67,64.39,45.69,244.0,Poor
38,Ahmedabad,2015-03-14,3,2015,Summer,83.92,108.015667,6.42,25.03,NaN,6.42,67.53,34.94,234.0,Poor
39,Ahmedabad,2015-03-15,3,2015,Summer,49.51,108.015667,3.10,14.16,NaN,3.10,48.33,37.95,219.0,Poor
40,Ahmedabad,2015-03-16,3,2015,Summer,30.76,108.015667,2.72,14.14,NaN,2.72,43.62,54.78,118.0,Moderate
41,Ahmedabad,2015-03-17,3,2015,Summer,50.29,108.015667,5.34,29.84,NaN,5.34,59.23,45.44,231.0,Poor
42,Ahmedabad,2015-03-18,3,2015,Summer,57.69,108.015667,25.36,29.48,NaN,25.36,58.33,52.87,286.0,Poor
43,Ahmedabad,2015-03-19,3,2015,Summer,105.06,108.015667,46.24,37.05,NaN,46.24,53.62,45.65,883.0,Severe
44,Ahmedabad,2015-03-20,3,2015,Summer,94.10,108.015667,22.14,36.53,NaN,22.14,61.31,46.77,720.0,Severe
45,Ahmedabad,2015-03-21,3,2015,Summer,111.89,108.015667,22.25,43.29,NaN,22.25,66.44,50.57,570.0,Severe
46,Ahmedabad,2015-03-22,3,2015,Summer,108.59,108.015667,25.38,39.34,NaN,25.38,75.80,46.68,589.0,Severe
47,Ahmedabad,2015-03-23,3,2015,Summer,130.76,108.015667,45.61,41.03,NaN,45.61,65.77,41.58,818.0,Severe
48,Ahmedabad,2015-03-24,3,2015,Summer,143.55,108.015667,27.30,31.15,NaN,27.30,50.98,35.38,737.0,Severe
49,Ahmedabad,2015-03-25,3,2015,Summer,165.07,108.015667,23.83,34.48,NaN,23.83,64.32,43.79,585.0,Severe

In [26]:
aqi.tail(50)

,City,Date,Month,Year,Season,PM2.5,PM10,NO,NO2,NH3,CO,SO2,O3,AQI,AQI_Bucket
24800,Visakhapatnam,2020-05-13,5,2020,Summer,8.42,50.06,2.09,14.05,11.07,0.11,6.96,14.28,49.0,Good
24801,Visakhapatnam,2020-05-14,5,2020,Summer,11.88,45.86,2.73,11.76,12.04,0.11,7.66,14.72,50.0,Good
24802,Visakhapatnam,2020-05-15,5,2020,Summer,11.07,42.11,3.17,11.71,11.96,0.11,9.70,17.92,44.0,Good
24803,Visakhapatnam,2020-05-16,5,2020,Summer,2.00,17.99,1.29,10.24,9.48,0.11,8.86,19.75,32.0,Good
24804,Visakhapatnam,2020-05-17,5,2020,Summer,6.30,17.76,1.09,12.21,7.40,0.11,8.56,17.14,23.0,Good
24805,Visakhapatnam,2020-05-18,5,2020,Summer,11.18,36.23,1.47,18.69,6.78,0.11,7.87,18.33,26.0,Good
24806,Visakhapatnam,2020-05-19,5,2020,Summer,26.88,76.70,2.00,28.32,7.56,0.11,10.13,24.73,52.0,Satisfactory
24807,Visakhapatnam,2020-05-20,5,2020,Summer,66.22,203.26,11.97,58.99,11.85,0.11,8.24,37.59,141.0,Moderate
24808,Visakhapatnam,2020-05-21,5,2020,Summer,45.53,150.21,3.50,48.13,12.68,0.11,11.82,33.44,145.0,Moderate
24809,Visakhapatnam,2020-05-22,5,2020,Summer,24.80,90.94,4.34,39.51,18.93,0.11,6.37,30.61,117.0,Moderate
24810,Visakhapatnam,2020-05-23,5,2020,Summer,15.91,81.11,3.27,23.59,13.57,0.11,8.48,37.58,79.0,Satisfactory
24811,Visakhapatnam,2020-05-24,5,2020,Summer,10.99,72.39,1.38,20.53,10.25,0.11,8.73,27.09,80.0,Satisfactory
24812,Visakhapatnam,2020-05-25,5,2020,Summer,18.69,75.86,2.76,21.06,10.77,0.11,7.19,24.62,74.0,Satisfactory
24813,Visakhapatnam,2020-05-26,5,2020,Summer,12.35,68.72,1.74,20.24,9.80,0.11,9.69,23.61,67.0,Satisfactory
24814,Visakhapatnam,2020-05-27,5,2020,Summer,26.60,121.23,1.69,20.04,8.58,0.63,8.42,28.80,54.0,Satisfactory
24815,Visakhapatnam,2020-05-28,5,2020,Summer,26.94,102.00,1.63,20.67,8.67,0.65,7.34,23.80,100.0,Satisfactory
24816,Visakhapatnam,2020-05-29,5,2020,Summer,16.71,62.53,2.60,23.89,10.62,0.63,7.79,24.10,87.0,Satisfactory
24817,Visakhapatnam,2020-05-30,5,2020,Summer,28.10,84.80,7.43,50.99,9.21,0.76,16.45,14.82,81.0,Satisfactory
24818,Visakhapatnam,2020-05-31,5,2020,Summer,21.22,79.53,2.38,24.88,11.03,0.57,5.43,17.49,40.0,Good
24819,Visakhapatnam,2020-06-01,6,2020,Monsoon,15.68,81.88,1.91,20.61,8.25,0.50,5.82,21.15,85.0,Satisfactory
24820,Visakhapatnam,2020-06-02,6,2020,Monsoon,9.91,43.30,2.81,19.91,9.16,0.47,8.78,19.68,50.0,Good
24821,Visakhapatnam,2020-06-03,6,2020,Monsoon,17.94,102.58,5.60,30.32,9.49,0.58,6.48,23.82,88.0,Satisfactory
24822,Visakhapatnam,2020-06-04,6,2020,Monsoon,19.14,77.06,4.12,35.57,8.82,0.68,7.19,25.56,71.0,Satisfactory
24823,Visakhapatnam,2020-06-05,6,2020,Monsoon,29.71,112.53,2.98,44.77,10.51,0.85,10.64,21.94,93.0,Satisfactory
24824,Visakhapatnam,2020-06-06,6,2020,Monsoon,21.66,74.97,3.38,38.42,8.63,0.64,7.02,28.86,101.0,Moderate
24825,Visakhapatnam,2020-06-07,6,2020,Monsoon,29.69,101.97,2.84,35.51,9.85,0.57,5.32,31.71,82.0,Satisfactory
24826,Visakhapatnam,2020-06-08,6,2020,Monsoon,31.14,125.15,6.55,41.56,9.71,0.64,6.61,36.65,115.0,Moderate
24827,Visakhapatnam,2020-06-09,6,2020,Monsoon,31.84,85.41,4.69,50.11,10.01,0.88,5.06,33.86,96.0,Satisfactory
24828,Visakhapatnam,2020-06-10,6,2020,Monsoon,32.55,79.28,4.78,44.59,9.34,0.69,5.90,35.06,92.0,Satisfactory
24829,Visakhapatnam,2020-06-11,6,2020,Monsoon,37.71,98.53,9.97,52.10,9.91,0.70,5.59,26.59,90.0,Satisfactory
24830,Visakhapatnam,2020-06-12,6,2020,Monsoon,37.67,76.27,12.17,53.59,9.85,0.97,5.74,17.35,84.0,Satisfactory
24831,Visakhapatnam,2020-06-13,6,2020,Monsoon,22.75,86.77,3.85,38.23,9.24,0.67,10.70,27.24,81.0,Satisfactory
24832,Visakhapatnam,2020-06-14,6,2020,Monsoon,21.33,83.23,2.81,34.56,9.78,0.58,9.37,29.44,88.0,Satisfactory
24833,Visakhapatnam,2020-06-15,6,2020,Monsoon,24.66,100.53,3.66,37.93,9.22,0.71,7.02,28.63,92.0,Satisfactory
24834,Visakhapatnam,2020-06-16,6,2020,Monsoon,21.06,80.51,6.67,40.33,8.81,0.63,11.09,21.69,83.0,Satisfactory
24835,Visakhapatnam,2020-06-17,6,2020,Monsoon,17.05,73.22,6.08,36.31,6.69,0.54,11.08,26.09,90.0,Satisfactory
24836,Visakhapatnam,2020-06-18,6,2020,Monsoon,21.16,88.80,4.94,42.96,3.22,0.68,11.05,27.65,71.0,Satisfactory
24837,Visakhapatnam,2020-06-19,6,2020,Monsoon,14.41,66.81,6.22,40.06,7.51,1.07,13.23,27.34,110.0,Moderate
24838,Visakhapatnam,2020-06-20,6,2020,Monsoon,26.67,86.29,3.78,37.36,15.05,0.74,11.76,41.97,74.0,Satisfactory
24839,Visakhapatnam,2020-06-21,6,2020,Monsoon,25.96,91.75,5.65,40.22,13.32,0.71,10.10,38.27,92.0,Satisfactory
24840,Visakhapatnam,2020-06-22,6,2020,Monsoon,33.17,108.22,5.58,42.45,13.70,0.73,13.65,34.85,95.0,Satisfactory
24841,Visakhapatnam,2020-06-23,6,2020,Monsoon,25.40,83.38,2.76,34.09,13.13,0.54,10.40,43.27,100.0,Satisfactory
24842,Visakhapatnam,2020-06-24,6,2020,Monsoon,34.36,90.90,1.22,23.38,14.45,0.56,10.92,35.12,86.0,Satisfactory
24843,Visakhapatnam,2020-06-25,6,2020,Monsoon,13.45,58.54,2.30,21.60,12.27,0.41,8.19,29.38,77.0,Satisfactory
24844,Visakhapatnam,2020-06-26,6,2020,Monsoon,7.63,32.27,5.91,23.27,11.15,0.46,6.87,19.90,47.0,Good
24845,Visakhapatnam,2020-06-27,6,2020,Monsoon,15.02,50.94,7.68,25.06,12.47,0.47,8.55,23.30,41.0,Good
24846,Visakhapatnam,2020-06-28,6,2020,Monsoon,24.38,74.09,3.42,26.06,11.99,0.52,12.72,30.14,70.0,Satisfactory
24847,Visakhapatnam,2020-06-29,6,2020,Monsoon,22.91,65.73,3.45,29.53,10.71,0.48,8.42,30.96,68.0,Satisfactory
24848,Visakhapatnam,2020-06-30,6,2020,Monsoon,16.64,49.97,4.05,29.26,10.03,0.52,9.84,28.30,54.0,Satisfactory
24849,Visakhapatnam,2020-07-01,7,2020,Monsoon,15.00,66.00,0.40,26.85,5.20,0.59,2.10,17.05,50.0,Good

In [27]:
aqi

,City,Date,Month,Year,Season,PM2.5,PM10,NO,NO2,NH3,CO,SO2,O3,AQI,AQI_Bucket
0,Ahmedabad,2015-01-29,1,2015,Winter,83.13,111.684815,6.93,28.71,NaN,6.93,49.52,59.76,209.0,Poor
1,Ahmedabad,2015-01-30,1,2015,Winter,79.84,111.684815,13.85,28.68,NaN,13.85,48.49,97.07,328.0,Very Poor
2,Ahmedabad,2015-01-31,1,2015,Winter,94.52,111.684815,24.39,32.66,NaN,24.39,67.39,111.33,514.0,Severe
3,Ahmedabad,2015-02-01,2,2015,Winter,135.99,144.907931,43.48,42.08,NaN,43.48,75.23,102.70,782.0,Severe
4,Ahmedabad,2015-02-02,2,2015,Winter,178.33,144.907931,54.56,35.31,NaN,54.56,55.04,107.38,914.0,Severe
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
24845,Visakhapatnam,2020-06-27,6,2020,Monsoon,15.02,50.940000,7.68,25.06,12.47,0.47,8.55,23.30,41.0,Good
24846,Visakhapatnam,2020-06-28,6,2020,Monsoon,24.38,74.090000,3.42,26.06,11.99,0.52,12.72,30.14,70.0,Satisfactory
24847,Visakhapatnam,2020-06-29,6,2020,Monsoon,22.91,65.730000,3.45,29.53,10.71,0.48,8.42,30.96,68.0,Satisfactory
24848,Visakhapatnam,2020-06-30,6,2020,Monsoon,16.64,49.970000,4.05,29.26,10.03,0.52,9.84,28.30,54.0,Satisfactory
24849,Visakhapatnam,2020-07-01,7,2020,Monsoon,15.00,66.000000,0.40,26.85,5.20,0.59,2.10,17.05,50.0,Good

In [28]:
aqi['NH3'].isnull().sum()

np.int64(2586)

In [29]:
aqi.isnull().sum()

City             0
Date             0
Month            0
Year             0
Season           0
PM2.5           52
PM10          2338
NO               0
NO2             31
NH3           2586
CO               0
SO2              0
O3             153
AQI              0
AQI_Bucket       0
dtype: int64

In [30]:
columns_to_fill = ['PM2.5', 'PM10', 'NO2', 'NH3', 'O3']

for col in columns_to_fill:
    aqi[col] = aqi[col].fillna(
        aqi.groupby(['City'])[col].transform('mean')
    )

In [31]:
aqi

,City,Date,Month,Year,Season,PM2.5,PM10,NO,NO2,NH3,CO,SO2,O3,AQI,AQI_Bucket
0,Ahmedabad,2015-01-29,1,2015,Winter,83.13,111.684815,6.93,28.71,NaN,6.93,49.52,59.76,209.0,Poor
1,Ahmedabad,2015-01-30,1,2015,Winter,79.84,111.684815,13.85,28.68,NaN,13.85,48.49,97.07,328.0,Very Poor
2,Ahmedabad,2015-01-31,1,2015,Winter,94.52,111.684815,24.39,32.66,NaN,24.39,67.39,111.33,514.0,Severe
3,Ahmedabad,2015-02-01,2,2015,Winter,135.99,144.907931,43.48,42.08,NaN,43.48,75.23,102.70,782.0,Severe
4,Ahmedabad,2015-02-02,2,2015,Winter,178.33,144.907931,54.56,35.31,NaN,54.56,55.04,107.38,914.0,Severe
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
24845,Visakhapatnam,2020-06-27,6,2020,Monsoon,15.02,50.940000,7.68,25.06,12.47,0.47,8.55,23.30,41.0,Good
24846,Visakhapatnam,2020-06-28,6,2020,Monsoon,24.38,74.090000,3.42,26.06,11.99,0.52,12.72,30.14,70.0,Satisfactory
24847,Visakhapatnam,2020-06-29,6,2020,Monsoon,22.91,65.730000,3.45,29.53,10.71,0.48,8.42,30.96,68.0,Satisfactory
24848,Visakhapatnam,2020-06-30,6,2020,Monsoon,16.64,49.970000,4.05,29.26,10.03,0.52,9.84,28.30,54.0,Satisfactory
24849,Visakhapatnam,2020-07-01,7,2020,Monsoon,15.00,66.000000,0.40,26.85,5.20,0.59,2.10,17.05,50.0,Good

In [32]:
aqi.isnull().sum()

City             0
Date             0
Month            0
Year             0
Season           0
PM2.5            0
PM10          1893
NO               0
NO2              0
NH3           1334
CO               0
SO2              0
O3             153
AQI              0
AQI_Bucket       0
dtype: int64

In [33]:
aqi[aqi['PM10'].isnull()]['City'].value_counts()

City
Lucknow    1893
Name: count, dtype: int64

In [34]:
aqi[aqi['NH3'].isnull()]['City'].value_counts()

City
Ahmedabad    1334
Name: count, dtype: int64

In [35]:
aqi[aqi['O3'].isnull()]['City'].value_counts()

City
Ernakulam    153
Name: count, dtype: int64

In [36]:
aqi.isnull().sum()

City             0
Date             0
Month            0
Year             0
Season           0
PM2.5            0
PM10          1893
NO               0
NO2              0
NH3           1334
CO               0
SO2              0
O3             153
AQI              0
AQI_Bucket       0
dtype: int64

In [37]:
aqi.shape

(24850, 15)

In [38]:
aqi.dtypes

City                  object
Date          datetime64[ns]
Month                  int32
Year                   int32
Season                object
PM2.5                float64
PM10                 float64
NO                   float64
NO2                  float64
NH3                  float64
CO                   float64
SO2                  float64
O3                   float64
AQI                  float64
AQI_Bucket            object
dtype: object

In [39]:
aqi['Dominant_Pollutant'] = aqi[['PM2.5', 'PM10', 'NO', 'NO2', 'NH3', 'CO', 'SO2', 'O3']].idxmax(axis=1)
aqi.head(5)

,City,Date,Month,Year,Season,PM2.5,PM10,NO,NO2,NH3,CO,SO2,O3,AQI,AQI_Bucket,Dominant_Pollutant
0,Ahmedabad,2015-01-29,1,2015,Winter,83.13,111.684815,6.93,28.71,NaN,6.93,49.52,59.76,209.0,Poor,PM10
1,Ahmedabad,2015-01-30,1,2015,Winter,79.84,111.684815,13.85,28.68,NaN,13.85,48.49,97.07,328.0,Very Poor,PM10
2,Ahmedabad,2015-01-31,1,2015,Winter,94.52,111.684815,24.39,32.66,NaN,24.39,67.39,111.33,514.0,Severe,PM10
3,Ahmedabad,2015-02-01,2,2015,Winter,135.99,144.907931,43.48,42.08,NaN,43.48,75.23,102.70,782.0,Severe,PM10
4,Ahmedabad,2015-02-02,2,2015,Winter,178.33,144.907931,54.56,35.31,NaN,54.56,55.04,107.38,914.0,Severe,PM2.5

In [40]:
aqi['PM2.5'].min()

np.float64(0.04)

In [41]:
aqi['PM2.5'].max()

np.float64(914.94)

In [42]:
np.linspace(0.04, 914.94, 5)

array([4.00000e-02, 2.28765e+02, 4.57490e+02, 6.86215e+02, 9.14940e+02])

In [43]:
conditions = [
    (aqi['PM2.5'] >= 0) & (aqi['PM2.5'] <= 30),
    (aqi['PM2.5'] >= 31) & (aqi['PM2.5'] <= 60),
    (aqi['PM2.5'] >= 61) & (aqi['PM2.5'] <= 90),
    (aqi['PM2.5'] > 90)
]

choices = ['Low', 'Medium', 'High', 'Very High']

aqi['PM2.5_Risk'] = np.select(conditions, choices, default='unknown')
aqi.head(5)

,City,Date,Month,Year,Season,PM2.5,PM10,NO,NO2,NH3,CO,SO2,O3,AQI,AQI_Bucket,Dominant_Pollutant,PM2.5_Risk
0,Ahmedabad,2015-01-29,1,2015,Winter,83.13,111.684815,6.93,28.71,NaN,6.93,49.52,59.76,209.0,Poor,PM10,High
1,Ahmedabad,2015-01-30,1,2015,Winter,79.84,111.684815,13.85,28.68,NaN,13.85,48.49,97.07,328.0,Very Poor,PM10,High
2,Ahmedabad,2015-01-31,1,2015,Winter,94.52,111.684815,24.39,32.66,NaN,24.39,67.39,111.33,514.0,Severe,PM10,Very High
3,Ahmedabad,2015-02-01,2,2015,Winter,135.99,144.907931,43.48,42.08,NaN,43.48,75.23,102.70,782.0,Severe,PM10,Very High
4,Ahmedabad,2015-02-02,2,2015,Winter,178.33,144.907931,54.56,35.31,NaN,54.56,55.04,107.38,914.0,Severe,PM2.5,Very High

In [44]:
aqi['PM2.5_Risk'].value_counts()

PM2.5_Risk
Medium       8255
Low          6571
Very High    5107
High         4353
unknown       564
Name: count, dtype: int64

In [45]:
aqi['Dominant_Pollutant'].value_counts()

Dominant_Pollutant
PM10     19025
PM2.5     3011
O3        1176
NH3        918
NO2        391
NO         191
SO2        137
CO           1
Name: count, dtype: int64

In [46]:
aqi.to_csv('E:\\project_aqi_pulse\\data\\aqi_cleaned.csv', index=False)

In [48]:
aqi.shape

(24850, 17)